import time
import sys
from images import *
from pro import *
def first():
   kyle()
   print("1) KYLE- You have the capability to drink large amounts of Monster Energy and you are broke. You are the definition of Chaotic Good. ")
   time.sleep(1)
   antivax()
   print("2) ANTI-VAX KID- You never got vaccinated.")
   time.sleep(1)
   normie()
   print("3) NORMIE- You are just a normal person who wanted to join in on the fun. There is nothing extremely special about you. You are like white bread.")
   time.sleep(1)
   karen()
   print("4) KAREN- You have a tannie hair cut, and you request to speak to the manager every single time you go somewhere. You are the stereotypical 40+ year old white suburban mom.")
   start = input("Who will you play as? ")
   if(start == "1"):
       print("You've chosen Kyle.")
   elif(start == "2"):
       print("YA DIED. Sorry not sorry. You didn’t make it past the fence. The rust invaded your immune system and wreckity wrecked it. Sucks for you. Why don’t you get vaccinated in the next life, maybe then you can have fun with cool kids.")
       sys.exit()
   elif(start == "3"):
       print("You've chosen Normie.")
   elif(start == "4"):
       print("You've chosen Karen.")
   desert()
   print("It is September 20, 2019. The time has come. You and a million other people have come to face your destiny. You will raid the notorious Area 51.")
   time.sleep(4)
   print("You must make it past the first fence.")
   fence()
   time.sleep(4)
   print("a) Naruto Run")
   time.sleep(1)
   print("b) Regularly run behind Naruto Runners")
   time.sleep(1)
   print("c) Moonwalk")
   time.sleep(1)
   print("d) Take Mom's car")
   q1 = input("Which option do you choose? ")
   if(q1 == "a"):
       print("You successfully made it through the base's first line of defense.")
   elif(q1 == "b"):
       print("You were grazed by a couple of bullets, but it was nothing too serious. You have open cuts and a low health.")
   elif(q1 == "c"):
       print("The spirit of Michael Jackson guided you. You were able to HE HE your way past the first line of defense.")
   elif(q1 == "d"):
       print("The car was badly damaged. Mom's totally going to kill you!")
   time.sleep(3)
   print("After making it through the first line of defense you find that most of your companions have fallen. RIP. You come to a fork in the road. There are two hallways to go down. You are now faced with a decision:")
   time.sleep(1)
   print("a) Go search for aliens down hallway 1")
   time.sleep(1)
   print("b) Look top secret documents in hallway 2")
   q2 = input("What option do you choose?")
   if(q2 == "a"):
       print("The areas where the aliens are kept are heavily guarded by human-killing robots. Beware, they are armed with deadly lasers and advanced technology.")
       time.sleep(1)
       #Aliens
       if(q1 == "b"):
           time.sleep(3)
           print("You are at a disadvantage. The air surrounding the aliens is filled with unique bacteria that is harmful to your human immune system. Since you have open wounds you are now sick. It is hard to breathe. Your health is even lower.")
       time.sleep(1)
       fourdoors()
       print("You come across 4 metal doors..")
       time.sleep(1)
       print("a) Door 1")
       time.sleep(1)
       print("b) Door 2")
       time.sleep(1)
       print("c) Door 3")
       time.sleep(1)
       print("d) Door 4")
       q3 = input("Which do you choose? ")
       if(q3 == "a" or q3 == "b" or q3 == "d"):
           weapon()
           print("You died. Robot guards were prepared to shoot on sight, and you took the bullet.")
           sys.exit()
       elif(q3 == "c"):
           print("Congratulations, you’ve made it through your first door. Be careful, you don’t know where all the guards are. As you approach a new corridor, you may..")
       elif(start == "4" and q3 == "a" or q3 == "b" or q3 == "c" or q3 == "d"):
           print("You have an advantage. Your supernatural senses of knowing where the managers/guards are; leads you away from danger.")
       time.sleep(1)
       print("a) Peek around the corner")
       time.sleep(1)
       print("b) Use a compact mirror to check the hall")
       time.sleep(1)
       print("c) Confidently walk")
       q4 = input("What's your choice? ")
       if(q4 == "a"):
           weapon()
           print("You died. There was a sniper robot and he took his shot when you poked your gigantic head around the corner. Be better next time.")
           sys.exit()
       elif(q4 == "b"):
           print("You were able to continue without being discovered. Good thinking.")
       elif(q4 == "c"):
           print("You ran into many workers along your way, but since you were so confident, they overlooked your lack of uniform and credentials and let you continue.")
       print("You come across a set of two doors. Door 1 has a slimy substance oozing out of the cracks of the door. Door 2 has big, visible dents that protrude out. ")
       time.sleep(1)
       print("a) Door 1")
       time.sleep(1)
       print("b) Door 2")
       time.sleep(1)
       q5 = input("What is your choice? ")
       if(q5 == "a"):
           print("You became doused with alien goo, and could no longer go any further in your journey because you left a trail and were soon caught.")
           sys.exit()
       elif(q5 == "b"):
           print("You were surprised that there was nothing in the room. You continue on. ")
       time.sleep(2)
       print("You are so close to finding where the aliens are stored. Your bones are jumping and you are extremely excited.")
       time.sleep(2)
       print("You come across the final hallway you have to pass through. You may..")
       time.sleep(1)
       print("a) Peek around the corner")
       time.sleep(1)
       print("b) Use a compact mirror to check the hall")
       time.sleep(1)
       print("c) Confidently walk")
       q6 = input("What is your choice? ")
       if(q6 == "a" or q6 == "b"):
           print("You realize there is a wall of armed robots blocking the room that contained the entrance to the alien cages. ")
           time.sleep(3)
           print("You could..")
           time.sleep(1)
           print("a) Find a path through the ventilation system")
           time.sleep(1)
           print("b) Go out, guns blazing")
           q11 = input("What is your choice? ")
           if(start == "1" and q11 == "a"):
               print("You made it through the vents.")
               time.sleep(2)
           elif(start == "3" and q11 == "a"):
               print("You had some close calls but you were able to make it.")
               time.sleep(2)
           elif(start == "4" and q11 == "a"):
               print("You were appalled at the amount of dust and cobwebs in the vents and knew it was violating health codes.")
               time.sleep(2)
               print("You couldn’t go any longer without complaining and went to go find a manager.")
               time.sleep(2)
               print("You forgot your mission and was caught looking for a person to complain to.")
               sys.exit()
               time.sleep(2)
           elif(q1 == "b" and q11 == "a"):
               print("you coughed in the vents because the dust on top of your weakened body was too much. You gave away your position and were caught.")
               sys.exit()
           elif(start == "1" and q11 == "b"):
               print("Your monstrous amount of energy— pun intended— overwhelmed the robots' motherboards and you were able to get past.")
               time.sleep(2)
           elif(start == "4" and q11 == "b"):
               print("your yoga classes did not help in fighting robots. You died.")
               sys.exit()
           elif(start == "3" and q11 == "b"):
               print("You fought a valiant, .2 second-long battle, but ultimately lost.")
               sys.exit()
           elif(q1 == "b" and q11 == "b"):
               print("With your already weakened health, one shot to the leg was all it took to have you yeeted off this mortal coil.")
               sys.exit()
           print("You come across a big room resembling the inside of a prison.")
           time.sleep(2)
           print("Upon closer inspection, you realize that the cells contain different kinds of aliens.")
           time.sleep(2)
           print("Congratulations! You've done it! You can now have your very own alien.")
           time.sleep(2)
           print("The End.")
       elif(q6 == "c"):
           weapon()
           print("You were shot at by a wall of killer robots. Apparently, the workers were given strict instructions not to go into that hallway because the robots were given orders to shoot anything that came into their sight.")               
           sys.exit()
   elif(q2 == "b"):
       print("The area where all the secrets are kept are heavily guarded by human guards. Beware these “humans” are top ranking soldiers, the best of the best, Navy Seals, with no sense of empathy. They will kill you with no regerts.")
       time.sleep(2)
       print("Despite this, you chose to reveal those secrets.")
       time.sleep(2)
       print("What a nerd.")
       time.sleep(1)
       print("As you walk down the hallway you realize you are coming to a locked door that requires a key card.")
       time.sleep(1)
       print("You may..")
       time.sleep(1)
       print("a) Knock")
       time.sleep(1)
       print("b) Hotwire")
       time.sleep(1)
       print("c) Turn around and go back home.")
       q7 = input("What is your choice? ")
       if(q7 == "a"):
           guard1()
           print("You got lucky. A security guard who was drinking in light of the raid let you in.")
       elif(start == "3" or start == "4" and q7 == "b"):
           print("You fail and fry yourself like KFC chicken. You do not have the pure monstrous rage of Kyle to save you.")
           sys.exit()
       elif(start == "1" and q7 == "b"):
           print("You succeed. Spending time with your sketchy cousin was worth it and streamlining cans of Monster Energy was the best decision you made in your life. ")
       elif(q7 == "d"):
           print("You go back home. You tried your best, but it wasn't good enough. You'll be known as a coward for the rest of your life.")
           sys.exit()
       time.sleep(1)
       print("You search some more and come to a corner. You have some quick choices to make:")
       time.sleep(1)
       print("a) Peek your head around the corner")
       time.sleep(1)
       print("b)Use a compact mirror to check the corridor")
       time.sleep(1)
       print("c) Confidently walk")
       q8 = input("What is your choice? ")
       if(q8 == "a" or q8 == "b"):
           guard2()
           print("You see people walking by. You quickly duck down and hide your body against the wall, remaining unseen.")
           time.sleep(3)
           print("You've been trekking through the halls of Area 51 for quite sometime now. You have ran out of food to snack on and your stomach is growling so loud that it might give you away if you continue any longer.")
           time.sleep(4)
           print("Do you..")
           time.sleep(1)
           print("a) Find the breakroom where you know food will be")
           time.sleep(1)
           print("b) Continue on and risk it")
           q8 = input("What is your choice? ")
           if(start == "3" and q8 == "a"):
               print("Congrats, your lack of uniqueness and your mediocre looks allows you to blend right in with other personnel and your satisfy your hunger.")
           elif(start == "1" and q8 == "a"):
               print("When you found the breakroom and saw there was no Monster Energy stocked and you threw a fit. You trashed the breakroom and were caught and arrested by security.")
               sys.exit()
           elif(start == "4" and q8 == "a"):
               print("You found the break room and were appalled at the food choices. You found the closest worker and demanded to speak to the manager. You forgot why you were here in the first place and got caught.")
               sys.exit()
           elif(q8 == "b"):
               print("You had some close calls, but were never noticed. Your hunger only further motivates you to persevere.")
           time.sleep(2)
           print("You feel it in your bones that you are almost there. You quickly walk past a hallway. You see that the Navy Seals are there, but they didn’t see you.")
           time.sleep(2)
           print("You may:")
           time.sleep(1)
           print("a) Go out, guns blazing")
           time.sleep(1)
           print("b) Try to crawl through the vent")
           q9 = input("What is your choice? ")
           if(start == "3" and q9 == "a"):
               guard2()
               print("You died. You were yeeted off this mortal coil by the soldiers standing guard.")
               sys.exit()
           elif(start == "1" and q9 == "a"):
               print("You succeed. The monster energy coursing through your veins made you bulletproof. The Navy seals’ bullets could not penetrate your skin. Since the bullets did not work on you, you were able to detonate the guards to dust.")
           elif(start == "4" and q9 == "a"):
               print("You succeeded. When you came running, you reminded the Navy Seals of their moms, and immediately became terrified to death. They apologized profusely and begged for you not to call their own mothers.")
           elif(start == "1" or start == "3" and q9 == "b"):  
               print("You successfully crawled through the vents with no trouble.")
           elif(start == "4" and q9 == "b"):
               print("You were appalled at the amount of dust and cobwebs in the vents and knew it was violating health codes. You couldn’t go any longer without complaining and went to go find a manager. You forgot your mission and was caught looking for a person to complain to.")
           time.sleep(2)
           print("To your dismay, you see that the Navy Seals were guarding a room full of nerds and not the top secrets.")
           time.sleep(2)
           print("You interrogate a nerd who is shaking like a chihuahuahuahua.")
           time.sleep(2)
           print("You find out they are in the process of digitizing the secrets into files. The answers to all the world’s secrets are in the room next door, but you need a key to get in.")
           time.sleep(3)
           print("a) Ask politely")
           time.sleep(1)
           print("b) Bully the nerds")
           q10 = input("What is your choice? ")
           if(q10 == "a"):
               print("You asked nicely and the nerd didn't want to make you angry. He agrees to give you the key.")
           elif(start == "1" and q10 == "b"):
               print("You slapped the nerd so hard that his great-grandmother could feel it. He immediately handed over the key.")
           elif(start == "4" and q10 == "b"):
               print("You snatched the key right from the nerd’s sweaty hands.")
           elif(start == "3" and q10 == "b"):
               print("A Navy Seal heard the commotion and immediately arrested you for picking on his little brother.")
               sys.exit()
           time.sleep(1)
           print("You made it. The world's top secrets are 10 feet to your right.")
           time.sleep(2)
           print("Adrenaline is rushing through your veins. You feel enlightened already.")
           time.sleep(2)
           print("You walk to the door and insert the key in.")
           time.sleep(1)
           print("It works and you step through the door frame. ")
           time.sleep(2)
           print("You come upon enormous room with shelves reaching to the ceiling with boxes of files containing secrets.")
           time.sleep(3)
           print("You open the first box you see and read the file.")
           time.sleep(2)
           print("You find the recipe for 100 percent bacteria and germ killing hand sanitizer.")
           print("Apparently the last digit of pi is 0,")
           time.sleep(1)
           print("there is a multiverse,")
           time.sleep(1)
           print("Game of Thrones Season 8 is being redone,")
           time.sleep(1)
           print("Tupac is alive and living in the Cayman islands,")
           time.sleep(1)
           print("the meaning of life is 42,")
           time.sleep(1)
           print("the secret ingredient in the Krabby Patty is crab,")
           time.sleep(1)
           print("Obama's last name is Barack,")
           time.sleep(1)
           print("and the person who let the dogs out was your future self.")
           time.sleep(2)
           print("You exit the building, flying away with the knowledge of a thousand sages.")
           time.sleep(2)
           print("The End.")
       elif(q8 == "c"):
           print("You ran right into a group of guards. They catch you and bring you to their boss.")
           sys.exit()   
